repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.7.4
          - sqlalchemy>=2.0.30
        files: ^src/.*\.py$
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ["-c", "pyproject.toml"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        exclude: ^data/
  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest (fast subset)
        entry: bash -c 'source .venv/bin/activate && pytest -q -k "not integration and not mvs"'
        language: system
        pass_filenames: false
        stages: [manual]
        types: [python]
      - id: pytest-full
        name: pytest (full)
        entry: bash -c 'source .venv/bin/activate && pytest -q'
        language: system
        pass_filenames: false
        stages: [manual]
        types: [python]
