<<<<<<< HEAD
version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: audiobook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/audiobook
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  dagster-webserver:
    build: .
    command: dagster-webserver -h 0.0.0.0 -p 3000 -f src/ops/repository.py
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/audiobook
    volumes:
      - .:/app
      - data:/app/data
    ports:
      - "3000:3000"
    depends_on:
      - db

  dagster-daemon:
    build: .
    command: dagster-daemon run
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/audiobook
    volumes:
      - .:/app
      - data:/app/data
    depends_on:
      - db

volumes:
  postgres_data:
  data:
=======
>>>>>>> 1774ed3 (chore: fresh-start: keep docs only)
