# Overrides for GPU development (XTTS v2 primary)
app:
  mode: dev-gpu

rendering:
  tts:
    primary: xtts_v2
    fallback: piper
    gpu_workers: 1

workers:
  cpu: 4
  gpu: 1

docker:
  use_gpu: true
