name: Branch and PR Guardrails

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  branch_name_check:
    name: Branch name follows feat/#123-short-desc
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check branch name pattern (PR head)
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          ref="$HEAD_REF"
          if [[ "$ref" == "main" || "$ref" == "master" || "$ref" == release/* ]]; then
            echo "Skipping protected branch: $ref"
            exit 0
          fi
          # Temporary allowance for snapshot branches while migrating to new conventions
          if [[ "$ref" == snapshot-* ]]; then
            echo "Allowing snapshot branch: $ref"
            exit 0
          fi
          if [[ ! "$ref" =~ ^(feat|fix|chore|docs|test|infra)/#[0-9]+-[a-z0-9-]+$ ]]; then
            echo "Branch name must match: <type>/#<issue>-<kebab-desc> (e.g., feat/#123-short-desc). Got: $ref" >&2
            exit 1
          fi

  pr_single_issue_check:
    name: PR links exactly one issue
    runs-on: ubuntu-latest
    needs: branch_name_check
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate linked issue count
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          body="$BODY"
          count=$(echo "$body" | grep -Eoi '\bfixes #[0-9]+' | wc -l | tr -d ' ')
          if [ "$count" -ne 1 ]; then
            echo "PR description must contain exactly one 'Fixes #<id>' reference (found $count)." >&2
            exit 1
          fi
