name: ci
on: [push, pull_request]
jobs:
  style-and-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Create local .venv & install dev deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Assert venv active
        run: |
          . .venv/bin/activate
          python - <<'PY'
import sys, os, pathlib
root = pathlib.Path.cwd()
expected = root/'.venv'
assert os.environ.get('VIRTUAL_ENV') == str(expected), f"VIRTUAL_ENV mismatch: {os.environ.get('VIRTUAL_ENV')} != {expected}"
assert pathlib.Path(sys.prefix).resolve() == expected.resolve(), f"sys.prefix mismatch: {sys.prefix} != {expected}"
print('[assert] venv OK:', sys.prefix)
PY
      - name: Ruff (auto-fix pass)
        run: .venv/bin/ruff check --fix . && .venv/bin/ruff format .
      - name: Ruff (verify clean)
        run: |
          .venv/bin/ruff check --diff .
          .venv/bin/ruff format --check .
          git diff --exit-code
      - name: mypy (strict)
        run: .venv/bin/mypy .
