name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["**"]
    paths:
      - '**/*.py'
      - 'src/**'
      - 'tests/**'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
      - 'Makefile'
  push:
    branches: ['main']
    paths:
      - '**/*.py'
      - 'src/**'
      - 'tests/**'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
      - 'Makefile'

jobs:
  build-311:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - name: Install uv
        run: python -m pip install -U pip uv
      - name: Sync dev dependencies (uv)
        run: uv pip install -r requirements-dev.txt
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest -q
