name: Project Automation

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled, ready_for_review]
  workflow_dispatch:

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check token present
        id: token
        shell: bash
        env:
          TOKEN: ${{ secrets.PROJECTS_TOKEN }}
        run: |
          if [ -n "${TOKEN}" ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/add-to-project@v1.0.2
        if: ${{ steps.token.outputs.present == 'true' }}
        with:
          project-url: https://github.com/users/jwardwell7077/projects/3
          github-token: ${{ secrets.PROJECTS_TOKEN }}

  wip-guard:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: Check PRs and warn if too many in review
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.search.issuesAndPullRequests({
              q: `org:${context.repo.owner} repo:${context.repo.repo} is:pr is:open review:required`,
            });
            const count = prs?.total_count ?? 0;
            core.notice(`Open PRs requiring review: ${count}`);
            if (count > 5) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: 'Heads up: More than 5 PRs appear to be in review. Consider reducing WIP to keep flow healthy.'
              });
            }

  missing-secret-hint:
    runs-on: ubuntu-latest
    steps:
      - name: Check token present
        id: token
        shell: bash
        env:
          TOKEN: ${{ secrets.PROJECTS_TOKEN }}
        run: |
          if [ -n "${TOKEN}" ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Show setup hint
        if: ${{ steps.token.outputs.present != 'true' }}
        run: |
          echo "PROJECTS_TOKEN secret is not set."
          echo "Create a classic PAT with 'project' and 'repo' scopes under your user, then add it as a repo secret named PROJECTS_TOKEN."
          echo "After that, re-run this workflow or re-label issues to auto-add to the project."
