name: Quality Gate

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -r requirements-dev.txt

      - name: Run quality gate
        run: |
          source .venv/bin/activate
          make quality_gate COMP_PATH=src || (echo "Quality gate failed" && exit 1)
      
      - name: Docs link check
        run: |
          source .venv/bin/activate
          make docs_link_check

      - name: Docs lint (mdformat + PyMarkdown)
        run: |
          source .venv/bin/activate
          make docs_lint

      - name: pre-commit (selected)
        run: |
          source .venv/bin/activate
          pre-commit run -a mdformat pymarkdown || (echo "pre-commit docs format/lint failed" && exit 1)
