name: Quality Gate

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "**" ]
    paths:
      - '**/*.py'
      - 'src/**'
      - 'Makefile'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/quality-gate.yml'
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.py'
      - 'src/**'
      - 'Makefile'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/quality-gate.yml'

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install uv
        run: python -m pip install -U pip uv

      - name: Install dev dependencies (uv)
        run: uv pip install -r requirements-dev.txt

      - name: Run quality gate
        env:
          PYTHONPATH: src
        run: |
          make quality_gate COMP_PATH=src || (echo "Quality gate failed" && exit 1)

      - name: Docs link check
        run: make docs_link_check

      - name: Docs lint (mdformat + PyMarkdown)
        run: make docs_lint

      - name: pre-commit (selected)
        run: pre-commit run -a mdformat pymarkdown || (echo "pre-commit docs format/lint failed" && exit 1)
