name: seedpack-latest
on:
  push:
    branches: [ main ]
    # Avoid infinite loops if the bot commits only seed_pack changes:
    paths-ignore:
      - "seed_pack/**"
  pull_request:
    branches: [ main ]

concurrency:
  group: seedpack-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-seedpack:
    # Skip if this run was triggered by our own bot commit
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11 + uv
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip uv
      - name: Ensure seed-pack deps
        run: uv pip install pyyaml

      - name: Generate seed pack
        run: |
          uv run python tools/seedpack/generate_seed_pack.py \
            --book mvs \
            --profiles data/voices/mvs_parler_profiles.yaml \
            --catalog  data/voices/parler_catalog.yaml

      - name: Mirror to seed_pack/latest and zip variants
        run: |
          ts=$(date +%F)
          rm -rf seed_pack/latest && mkdir -p seed_pack/latest
          cp -r seed_pack/$ts/* seed_pack/latest/

          # Build chat_min.zip and latest.zip
          cd seed_pack
          # chat_min files: use index.json.chat_min subset
          python - <<'PY'
import json, pathlib, zipfile
root = pathlib.Path(".")
idx = json.loads((root/"latest/index.json").read_text())
subset = idx.get("chat_min", [])
with zipfile.ZipFile("chat_min.zip", "w", zipfile.ZIP_DEFLATED) as z:
    for rel in subset:
        p = root/"latest"/rel
        z.write(p, arcname=pathlib.Path(rel).name if not rel.startswith("modules/") else rel)
with zipfile.ZipFile("latest.zip", "w", zipfile.ZIP_DEFLATED) as z:
    for p in (root/"latest").rglob("*"):
        if p.is_file():
            z.write(p, arcname=str(p.relative_to(root/"latest")))
print("Wrote chat_min.zip and latest.zip")
PY

      - name: Commit seed_pack changes (push events only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add seed_pack
          git commit -m "Seed pack refresh [skip ci]" || echo "No changes to commit"
          git push
